### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Mahdi-ME** [Elinvention/efibootmgr-gui#3]
This error is receiving:
$ sudo python efibootmgr-gui.py

Traceback (most recent call last):
  File "efibootmgr-gui.py", line 9, in <module>
    import efibootmgr
  File "/home/m/Downloads/efibootmgr-gui-master/efibootmgr.py", line 7
    print(*cmd)
          ^
SyntaxError: invalid syntax

**Comment by Elinvention** [comment]
You need to run it with python3 and you don't need sudo :smile:
