### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Itamiko** [Elinvention/efibootmgr-gui#8]
info:
os: Arch Linux
Python 3.7.3

```
findmnt --noheadings --output SOURCE --target /boot/efi
/dev/sda2
Traceback (most recent call last):
  File "efibootmgr-gui.py", line 328, in <module>
    win = EFIWindow()
  File "efibootmgr-gui.py", line 218, in __init__
    self.store = EFIStore(self)
  File "efibootmgr-gui.py", line 93, in __init__
    self.refresh()
  File "efibootmgr-gui.py", line 135, in refresh
    self.reorder()
  File "efibootmgr-gui.py", line 102, in reorder
    super().reorder(items)
TypeError: Item 4: Must be number, not NoneType
```

**Comment by Elinvention** [comment]
Could you send me the output of `efibootmgr`?

**Comment by Itamiko** [comment]
```
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001,2001,2002,2004
Boot0000* Fedora
Boot0001* Windows Boot Manager
Boot0002* Fedora
Boot0003* Windows Boot Manager
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot3000* Internal Hard Disk or Solid State Disk
Boot3004* Internal Hard Disk or Solid State Disk
```
@Elinvention

**Comment by Elinvention** [comment]
Ah sorry, what I actually needed was `efibootmgr -v`. However I think the problem is that BootOrder lists 5 items, but there are actually 8 to order. So I cannot assume that BootOrder is a total order. I wonder what can I do about that?
